package com.example.EmployeeMgmt.model;


import org.springframework.data.annotation.Id;

import java.util.Date;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "Employee")
public class Employee {

  public static final String SEQUENCE_NAME = "employee_sequences";


  @Id
  String empId;
  int user_type;                                                      //(Set by Admin at generation)
  String name;                                                        //(Set by Admin at generation)
  String DOJ;                                                           //(Set by Admin at generation)
  String password;                                          //(Generated by Admin, self-update-able)
  String phone;                                                //(Self-editable pending HR approval)
  String email;                                                //(Self-editable pending HR approval)
  String role;                                                                         //(Set by HR)
  Float salary;                                                                        //(Set by HR)
  String increment_status;                                                             //(Set by HR)
  String security_clearance;                                                        //(Set by Admin)
  String location;                                                                  //(Set by Admin)

  //Constructor
  public Employee(String empId, int user_type, String name, String DOJ, String password,
      String phone, String email, String role, Float salary, String increment_status,
      String security_clearance, String location) {
    super();
    this.empId = empId;
    this.user_type = user_type;
    this.name = name;
    this.DOJ = DOJ;
    this.password = password;
    this.phone = phone;
    this.email = email;
    this.role = role;
    this.salary = salary;
    this.increment_status = increment_status;
    this.security_clearance = security_clearance;
    this.location = location;
  }

  //Blank Constructor
  public Employee() {
  }

  //Getters and Setters

  public String getEmpId() {  return empId;  }
  public void setEmpId(String empId) { this.empId = empId;  }

  public int getUser_type() {
    return user_type;
  }
  public void setUser_type(int user_type) {
    this.user_type = user_type;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String getDOJ() {
    return DOJ;
  }
  public void setDOJ(String DOJ) {
    this.DOJ = DOJ;
  }

  public String getPassword() {   return password;  }
  public void setPassword(String password) {
    this.password = password;
  }

  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  public String getRole() {
    return role;
  }
  public void setRole(String role) {
    this.role = role;
  }

  public Float getSalary() {
    return salary;
  }
  public void setSalary(Float salary) {
    this.salary = salary;
  }

  public String getIncrement_status() {
    return increment_status;
  }
  public void setIncrement_status(String increment_status) {
    this.increment_status = increment_status;
  }

  public String getSecurity_clearance() { return security_clearance;  }
  public void setSecurity_clearance(String security_clearance) {
    this.security_clearance = security_clearance;
  }

  public String getLocation() {   return location;  }
  public void setLocation(String location) {  this.location = location;  }

  //toString
  @Override
  public String toString() {
    return "Employee{" +
        "empId='" + empId + '\'' +
        ", user_type=" + user_type +
        ", name='" + name + '\'' +
        ", DOJ=" + DOJ +
        ", password='" + password + '\'' +
        ", phone='" + phone + '\'' +
        ", email='" + email + '\'' +
        ", role='" + role + '\'' +
        ", salary=" + salary +
        ", increment_status='" + increment_status + '\'' +
        ", security_clearance='" + security_clearance + '\'' +
        ", location='" + location + '\'' +
        '}';
  }


}
